### ISSUE TITLE
Too strict assumption on body schema location

### ISSUE THREAD

**Issue by sergburn** [PayU/api-schema-builder#43]
This code in open-api3.js

```
  const requestPath = `paths[${currentPath}][${currentMethod}].requestBody.content[${contentType}].schema`;
  const dereferencedBodySchema = get(dereferenced, requestPath);
  const referencedBodySchema = get(referenced, requestPath);
```

assumes that request body content definition is always given inline within [Operation Object](https://swagger.io/specification/#operationObject)'s requestBody field (since it is expected to be found in referenced schema), while by OpenAPI 3 definition there can be a reference as well.

For example:

```
/path:
  post:
    requestBody:
      $ref: '#/components/requestBodies/Body'

components:
  requestBodies:
    Body:
      required: true
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/BodySchema'
```

For such schema body validation set is empty. Please correct this.

**Comment by sergburn** [comment]
Thanks, version 1.2.2 fixes this.
(I checked with response body validation only, but since the code is same I assume it would also work in the above mentioned request body case as well)

**Comment by kobik** [comment]
@sergburn , can we close this?

**Comment by sergburn** [comment]
Yes, thanks again for fixing it!
