### ISSUE TITLE
Getting rid of unmaintained dependency, core-js@2

### ISSUE THREAD

**Issue by sergburn** [PayU/api-schema-builder#53]
Do you think it's possible to upgrade swagger-parser dependency to get rid of this warning?

`warning api-schema-builder > swagger-parser > z-schema > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.`

z-schema upgraded core-js to v3 (3.2.1) in 4.1.1 and swagger-parser uses this since 8.0.1. 
z-schema dropped core-js since 4.2.0 and swagger-parser upgraded to it in 8.0.4.

**Comment by kibertoad** [comment]
@sergburn Try updating the version of the library that you are using. I believe this has already happened in https://github.com/PayU/api-schema-builder/pull/45

**Comment by sergburn** [comment]
Of course! Thank you!
